### ISSUE TITLE
Why the `patch_nums` are (1, 2, 3, 4, 5, 6, 8, 10, 13, 16)

### ISSUE THREAD

**Issue by constroy** [FoundationVision/VAR#101]
https://github.com/FoundationVision/VAR/blob/cf0321a5ca7a0ca2dcc14fcc603b9a032d868730/models/var.py#L27

While in the paper, it seems to be a power of a, 

> For VAR, it needs us to define the resolution sequense (h1, w1, h2, w2, . . . , hK, wK) for autoregres-
sive generation, where hi, wi are the height and width of the VQ code map at the i-th autoregressive step, and hK = h, wK = w reaches the final resolution. Suppose nk = hk = wk for all 1 ≤ k ≤ K
and n = h = w, for simplicity. We set the resolutions as nk = a^(k−1) where a > 1 is a constant such that a^(K−1) = n.

**Comment by iFighting** [comment]
> https://github.com/FoundationVision/VAR/blob/cf0321a5ca7a0ca2dcc14fcc603b9a032d868730/models/var.py#L27
> 
> While in the paper, it seems to be a power of a,
> 
> > For VAR, it needs us to define the resolution sequense (h1, w1, h2, w2, . . . , hK, wK) for autoregres-
> > sive generation, where hi, wi are the height and width of the VQ code map at the i-th autoregressive step, and hK = h, wK = w reaches the final resolution. Suppose nk = hk = wk for all 1 ≤ k ≤ K
> > and n = h = w, for simplicity. We set the resolutions as nk = a^(k−1) where a > 1 is a constant such that a^(K−1) = n.

@constroy In fact, this patch_nums can be dynamically designed, you can refer to our latest paper https://github.com/FoundationVision/Infinity
