### ISSUE TITLE
Paper doesn't mention which GPU used

### ISSUE THREAD

**Issue by utkuoguzman** [FoundationVision/VAR#102]
Hi,
Your paper doesn't mention which GPU used. Can you tell me which one you utilized?
Thanks.

**Comment by iFighting** [comment]
It can be trained on any type of GPUS.

**Comment by utkuoguzman** [comment]
Your paper gave inference time results. If one knows which GPU achieved those, one can roughly extrapolate for the performances on other GPUs. Hence reporting GPU name is important for the people who care about inference times.

**Comment by iFighting** [comment]
> Your paper gave inference time results. If one knows which GPU achieved those, one can roughly extrapolate for the performances on other GPUs. Hence reporting GPU name is important for the people who care about inference times.

@utkuoguzman The inference time is tested on A100.
