### ISSUE TITLE
🚨 Ethical Concerns in AI Research 🚨

### ISSUE THREAD

**Issue by var-integrity-report** [FoundationVision/VAR#104]
To the AI community:

The NeurIPS 2024 Best Paper Award 🏆 was given to "Visual Autoregressive Modeling: Scalable Image Generation via Next-Scale Prediction (VAR)". While technically impressive, serious misconduct by the first author (Keyu Tian) undermines the integrity of our field.

🔍 Why this matters:
Ethical standards are the foundation of trust in academia. Misconduct directly harms the credibility of AI research and NeurIPS itself.

We urge the community to reconsider this award and prioritize transparency, integrity, and accountability.

📜 Full report with evidence included.  Let’s protect the values that drive progress in AI.

https://var-integrity-report.github.io/

**Comment by magacc1** [comment]
Posting here to request that you address the concerns publicly rather than just "close the issue"

**Comment by iFighting** [comment]
> Posting here to request that you address the concerns publicly rather than just "close the issue"

@magacc1 Thanks for your remind. We'll find out what happened, If there is an update will reply here

**Comment by limesqueezy** [comment]
> > Posting here to request that you address the concerns publicly rather than just "close the issue"
> 
> @magacc1 Thanks for your remind. We'll find out what happened, If there is an update will reply here

There's literally tons of news and theories floating around regarding this paper, stop playing the PRC card and disclose what happened. 

Research is not politics.

https://www.reuters.com/technology/artificial-intelligence/bytedance-seeks-11-mln-damages-intern-ai-breach-case-report-says-2024-11-28/

https://www.reddit.com/r/MachineLearning/comments/1hctf36/d_the_winner_of_the_neurips_2024_best_paper_award/

https://news.ycombinator.com/item?id=42399182
