### ISSUE TITLE
The question about Figure 4, stage 2

### ISSUE THREAD

**Issue by AlbertLin0** [FoundationVision/VAR#115]
**Description** 
in the training process, $r_3$ can attend to $r_1, r_2$, correspondingly, the token maps of each scale are connected together with a attention mask during the training. But in the inference process, $r_3$ only attend to $r_2$. 
**My thought** 
i think the inference process is authors' expect, and the training process is for convenience according to the parameter "progress training". 
**My Question**
Whether the training of the model uses progress training？ 

THANKS,

**Comment by Kumbong** [comment]
I think in the inference a kv cache is used , so effectively it attends to everything before

**Comment by iFighting** [comment]
@Kumbong @AlbertLin0 
Yes, in the inference a kv cache is used, so the current scale attends to all previous scales before

**Comment by AlbertLin0** [comment]
@Kumbong @iFighting 
i get it, thanks!

**Comment by iFighting** [comment]
Since the question is answered, i close the issue
