### ISSUE TITLE
Keep getting this error in demo_sample.ipynb 

### ISSUE THREAD

**Issue by Aibecool174** [FoundationVision/VAR#18]
***[<ipython-input-10-c6558a80a848>](https://localhost:8080/#) in <cell line: 10>()***
      ***8 setattr(torch.nn.Linear, 'reset_parameters', lambda self: None)     # disable default parameter init for faster speed***
     ***9 setattr(torch.nn.LayerNorm, 'reset_parameters', lambda self: None)  # disable default parameter init for faster speed***
***---> 10 from models import VQVAE, build_var***
    *** 11 ***
     ***12 MODEL_DEPTH = 16    # TODO: =====> please specify MODEL_DEPTH <=====***

***ModuleNotFoundError: No module named 'models'***

but when downloading "Models" Module...

***Using cached models-0.9.3.tar.gz (16 kB)***
  ***error: subprocess-exited-with-error***
  
  ***× python setup.py egg_info did not run successfully.***
  ***│ exit code: 1***
  ***╰─> See above for output.***
  
 ***note: This error originates from a subprocess, and is likely not a problem with pip.***
  ***Preparing metadata (setup.py) ... error***
***error: metadata-generation-failed***

***× Encountered error while generating package metadata.***
***╰─> See above for output.***

***note: This is an issue with the package mentioned above, not pip.***
***hint: See above for details.***

**Comment by keyu-tian** [comment]
hi @Aibecool174 you need to download our models folder (https://github.com/FoundationVision/VAR/tree/main/models), not a python library named `models`.

**Comment by Aibecool174** [comment]
hmm, there are new errors in the model folders .py files saying "Import ".###" could not be resolvedPyright(reportMissingImports)" to imports that are ALL already in the VAR respiratory, even after restarting runtime
