### ISSUE TITLE
9 am UTC already past, code and models?

### ISSUE THREAD

**Issue by yqy2001** [FoundationVision/VAR#2]

**Comment by keyu-tian** [comment]
@yqy2001 we've met network issue in submitting checkpoints to huggingface. I've post some inference codes in this repo you can kindly check them. Once huggingface models're ready I'll ping you here again🤝.

**Comment by yqy2001** [comment]
Great! Thanks for the prompt response.

**Comment by keyu-tian** [comment]
Hi @yqy2001 now our [inference example](https://github.com/FoundationVision/VAR/blob/main/demo_sample.ipynb), [demo platform](https://var.vision/demo), and [model weights](https://huggingface.co/FoundationVision/var) are ready. I'm cleaning up the training code and it'll be ready in the very few days. Stay tuned❤️

**Comment by yqy2001** [comment]
> Hi @yqy2001 now our [inference example](https://github.com/FoundationVision/VAR/blob/main/demo_sample.ipynb), [demo platform](https://var.vision/demo), and [model weights](https://huggingface.co/FoundationVision/var) are ready. I'm cleaning up the training code and it'll be ready in the very few days. Stay tuned❤️

Great work! Thank you.

**Comment by keyu-tian** [comment]
@yqy2001 our training codes & scripts are released so im gonna close this. Thank you and hope you enjoy playing with VAR!
