### ISSUE TITLE
关于并行解码的疑问(Questions About Parallel Decoding)

### ISSUE THREAD

**Issue by helloheshee** [FoundationVision/VAR#24]
您好, 感谢您杰出的工作. 我对于并行解码和用交叉熵损失仍有疑问, 这假设了同一分辨率下每个token是独立的, 这是否能或为什么能对一个分辨率下的token良好建模. 假设一个场景, 如果总共只有两个样本: X0: (1, 2), X1: (2, 1), 如果用长度为2的查询向量并行解码, 如果用独立的交叉熵进行训练, 则模型学到的分布就是 查询向量->[0.5, 0.5], 而这样在后面采样时会等概率地采样到(1, 1), (1, 2), (2, 1), (2, 2), 这样就和真实分布不一样了. 不知是否我哪里理解的有问题, 还请不吝赐教.

(Thank you for your outstanding work. I still have some doubts regarding parallel decoding and the use of cross-entropy loss. This assumes that each token is independent at the same resolution, which raises the question of whether and why this approach can effectively model tokens at a given resolution.

Consider a scenario where there are only two samples: X0: (1, 2) and X1: (2, 1). If we use a query vector of length 2 for parallel decoding and train with independent cross-entropy, the distribution the model learns would be a uniform one, mapping the query vector to ->[0.5, 0.5]. This results in an equal probability of sampling (1, 1), (1, 2), (2, 1), and (2, 2) during subsequent sampling, which deviates from the true distribution. I am unsure if there's a misunderstanding on my part, and I would greatly appreciate your guidance on this matter.)

**Comment by keyu-tian** [comment]
That is an ideal case. If you think about the fact that all token maps (r1, r2, ..., rK) should be summed up to get a complete \hat{f}, this "independency" can be acceptable. When you sample ri, all (r1, r2, ..., r_{i-1}) can be seen. So to some extent, you can suppose all tokens in ri is independent to each other, that is, p(ri_11, ri_12, ..., ri_hw) = p(ri_11) * p(ri_12) * ... * p(ri_hw). Under this assumption, the parallel decoding is OK.

**Comment by helloheshee** [comment]
> In the case of 'X0: (token0=1, token1=2), X1: (token0=2, token1=1)', token0 and token1 are not independent to each other. But in VAR, we can assume each token within r_i scale can be independent to each other.
> 
> If you think about the fact that all token maps (r1, r2, ..., rK) should be summed up to get a complete \hat{f} (or in other words, we decompose an image feature map f into K components r1 to rK), this "independency" of tokens on a particular r_i can be acceptable. When you sample r_i, all preceding components (r1, r2, ..., r_{i-1}) are visible, allowing you to reasonably assume independence among the tokens within r_i, that is, p(r_i^{1,1}, r_i^{1,2}, ..., r_i^{h,w} | r_{<i}) = p(r_i^{1,1} | r_{<i}) * p(r_i^{1,2} | r_{<i}) * ... * p(r_i^{h,w} | r_{<i}). Under this assumption, the parallel decoding is OK.
> 
> Why this assumption is reasonable: To decode r_i, depending on all r_{<i} is enough, due to the locality of the multi-scale token map pyramid. Considering you're generating the top of a pyramid (a single token in r_i). You don't need to look at the tops of other pyramids (the other tokens in r_i), because you can already see all bottom tokens of all r_{<i}, and they can provide enough information.
> 
> So in short, in the context of VAR, tokens at a given r_i level can be assumed independent (but they can still condition on all tokens in preceding token maps r_{<i}), which addresses the concern you mentioned.
> 
> I think this assumption will be broken if VAR only has 1 scale. But it holds when VAR has many scales.

Thank you for your prompt and detailed response. I have another query regarding this matter: during the parallel decoding process in the model, the tokens are not actually independent because self-attention is used, which creates dependencies among the tokens. However, when calculating the cross-entropy loss and during sampling, there seems to be an underlying assumption that the tokens within the same layer are independent. This inconsistency is precisely what surprises me about its effectiveness.

Additionally, while it is true that at higher layers (denoted as  r_i), the model can maintain the independence of tokens by conditioning on the previous layers, at lower layers where there are fewer conditions, it becomes challenging to argue that the tokens can still be sampled independently. I attempted to examine the generated demo samples to find instances where this sampling method might lead to anomalies, but I found that it works quite well. Therefore, I speculate that the VAR architecture might perform well when conditioned on categories with small inter-class differences, but I am skeptical about its effectiveness in unconditional generation or on datasets with larger inter-class differences.

**Comment by keyu-tian** [comment]
thank you @helloheshee for such insightful thoughts! I agree with that the self-attentions can be helpful for enhancing interactions among tokens, especially for those early scales. As for the inter-class difference, I would suggest you to try a lower `cfg` (e.g., 1.5). I feel VAR still demonstrates good diversity even within one class, but a lower `cfg` is needed.
