### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for VAR in demo_sample.ipynb

### ISSUE THREAD

**Issue by sunqiang85** [FoundationVision/VAR#25]
var.load_state_dict(torch.load(var_ckpt, map_location='cpu'), strict=True)

RuntimeError: Error(s) in loading state_dict for VAR:
	Unexpected key(s) in state_dict: "blocks.0.attn.scale_mul_1H11", "blocks.1.attn.scale_mul_1H11", "blocks.2.attn.scale_mul_1H11", "blocks.3.attn.scale_mul_1H11", "blocks.4.attn.scale_mul_1H11", "blocks.5.attn.scale_mul_1H11", "blocks.6.attn.scale_mul_1H11", "blocks.7.attn.scale_mul_1H11", "blocks.8.attn.scale_mul_1H11", "blocks.9.attn.scale_mul_1H11", "blocks.10.attn.scale_mul_1H11", "blocks.11.attn.scale_mul_1H11", "blocks.12.attn.scale_mul_1H11", "blocks.13.attn.scale_mul_1H11", "blocks.14.attn.scale_mul_1H11", "blocks.15.attn.scale_mul_1H11".

**Comment by keyu-tian** [comment]
hi @sunqiang85 maybe you should git pull to get the latest demo code

**Comment by CRH400AF-A** [comment]
Hi, I get the latest code already but a similar error.

RuntimeError: Error(s) in loading state_dict for VAR:
	Missing key(s) in state_dict: "blocks.0.attn.scale_mul_1H11", "blocks.1.attn.scale_mul_1H11", "blocks.2.attn.scale_mul_1H11", "blocks.3.attn.scale_mul_1H11", "blocks.4.attn.scale_mul_1H11", "blocks.5.attn.scale_mul_1H11", "blocks.6.attn.scale_mul_1H11", "blocks.7.attn.scale_mul_1H11", "blocks.8.attn.scale_mul_1H11", "blocks.9.attn.scale_mul_1H11", "blocks.10.attn.scale_mul_1H11", "blocks.11.attn.scale_mul_1H11", "blocks.12.attn.scale_mul_1H11", "blocks.13.attn.scale_mul_1H11", "blocks.14.attn.scale_mul_1H11", "blocks.15.attn.scale_mul_1H11", "blocks.16.attn.scale_mul_1H11", "blocks.17.attn.scale_mul_1H11", "blocks.18.attn.scale_mul_1H11", "blocks.19.attn.scale_mul_1H11", "blocks.20.attn.scale_mul_1H11", "blocks.21.attn.scale_mul_1H11", "blocks.22.attn.scale_mul_1H11", "blocks.23.attn.scale_mul_1H11"
	
	
Here is demo_sample.ipynb. I only changed the model_depth=24 for I use var_d24.pth. 


################## 1. Download checkpoints and build models
import os
import os.path as osp
import torch, torchvision
import random
import numpy as np
import PIL.Image as PImage, PIL.ImageDraw as PImageDraw
setattr(torch.nn.Linear, 'reset_parameters', lambda self: None)     # disable default parameter init for faster speed
setattr(torch.nn.LayerNorm, 'reset_parameters', lambda self: None)  # disable default parameter init for faster speed
from models import VQVAE, build_vae_var

MODEL_DEPTH = 24    # TODO: =====> please specify MODEL_DEPTH <=====
assert MODEL_DEPTH in {16, 20, 24, 30}


# download checkpoint
hf_home = 'https://huggingface.co/FoundationVision/var/resolve/main'
vae_ckpt, var_ckpt = 'vae_ch160v4096z32.pth', f'var_d{MODEL_DEPTH}.pth'
if not osp.exists(vae_ckpt): os.system(f'wget {hf_home}/{vae_ckpt}')
if not osp.exists(var_ckpt): os.system(f'wget {hf_home}/{var_ckpt}')

# build vae, var
patch_nums = (1, 2, 3, 4, 5, 6, 8, 10, 13, 16)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
if 'vae' not in globals() or 'var' not in globals():
    vae, var = build_vae_var(
        V=4096, Cvae=32, ch=160, share_quant_resi=4,    # hard-coded VQVAE hyperparameters
        device=device, patch_nums=patch_nums,
        num_classes=1000, depth=MODEL_DEPTH, shared_aln=False,
    )

# load checkpoints
vae.load_state_dict(torch.load(vae_ckpt, map_location='cpu'), strict=True)
var.load_state_dict(torch.load(var_ckpt, map_location='cpu'), strict=True)
vae.eval(), var.eval()
for p in vae.parameters(): p.requires_grad_(False)
for p in var.parameters(): p.requires_grad_(False)
print(f'prepare finished.')

**Comment by CRH400AF-A** [comment]
It seems that var_d24.pth has some errors. I changed it to var_d20.pth and everything is fine. 
Maybe var_d24.pth needs update (in HF)?

**Comment by lolikonloli** [comment]
replace MODEL_DEPTH and restart your jupyter notebook. if not, it will use old model to load new ckpt.
