### ISSUE TITLE
Training resources

### ISSUE THREAD

**Issue by songtianhui** [FoundationVision/VAR#26]
Hello, thanks for your excellent work!
Can you share the computation resources for training VAR? Basically such as the number of GPUs and training days per epoch.
This would be of great help!

**Comment by keyu-tian** [comment]
@songtianhui Training VAR-d16 for 200 epochs on ImageNet 256x256 costs 2.5 days on 16 A100s. Training VAR-d30 for 350 epochs on ImageNet 512x512 with progressive training requires 256 A100 for around 4 days.

We'll add these in the new version of paper.
