### ISSUE TITLE
flash-atten相关问题

### ISSUE THREAD

**Issue by Silentssss** [FoundationVision/VAR#27]
你好，有个flash-atten的问题想请教下，当我想使能flash-attn时，我发现以下图1的逻辑根本走不进去，为此我打印了self.using_flash、attn_bias、qkv.dtype，最后发现attn_bias一直不是None（图2）
图1：
![image](https://github.com/FoundationVision/VAR/assets/108161275/2e65feea-0f95-4035-8bae-887ee2038931)
图2：
![image](https://github.com/FoundationVision/VAR/assets/108161275/e56d39da-8f12-4471-80cc-6431b94f85f8)

于是我将代码修改成以下逻辑：
`using_flash = self.using_flash and attn_bias is None and qkv.dtype != torch.float32`
修改为
`using_flash = self.using_flash and qkv.dtype != torch.float32`

`assert attn_bias is None and qkv.dtype != torch.float32`
修改为
`assert qkv.dtype != torch.float32`
但最后报了如图3的错误
图3：
![image](https://github.com/FoundationVision/VAR/assets/108161275/88a03b2e-42a7-4128-9f26-b49936c52955)

于是我继续打印输入的q、k、v的dtype（如图4）
图4：
![image](https://github.com/FoundationVision/VAR/assets/108161275/59e5509c-34dd-47d4-b768-8839e7ca10bd)
最后在代码中添加以下逻辑后功能才OK
![image](https://github.com/FoundationVision/VAR/assets/108161275/4cec3137-cd74-45e0-b1d4-25939e87d619)
请问这是已知bug吗，麻烦请检查下呢，或者是我哪里操作不对吗，请指导下，最后是我的运行命令
`torchrun --nproc_per_node=8 --nnodes=8 --node_rank=1 train.py 
  --depth=16 --bs=384 --ep=200 --fp16=1 --alng=1e-3 --wpe=0.1 --afuse=False`

**Comment by Silentssss** [comment]
参数写错了，以下为执行命令
`torchrun --nproc_per_node=8 --nnodes=1 --node_rank=0  train.py  --depth=16 --bs=384 --ep=200 --fp16=1 --alng=1e-3 --wpe=0.1 --afuse=False`

**Comment by keyu-tian** [comment]
hi @Silentssss 这个地方不能使用flash-attn，因为存在attention mask（attn_bias）不能忽视，而flash-attn不支持自定义mask

**Comment by Silentssss** [comment]
但是训练时如果走xformers的memory_efficient_attention也是报错的，q、k的dtype为float32，v为float16
![image](https://github.com/FoundationVision/VAR/assets/108161275/4f972ac2-1c03-448a-b4f7-92b8090faad7)

**Comment by keyu-tian** [comment]
Thanks @Silentssss, i fixed this xformers type error in the latest commit.
