### ISSUE TITLE
Dtype error with flash-attention 

### ISSUE THREAD

**Issue by ThisisBillhe** [FoundationVision/VAR#30]
This error occurs when sampling with pretrained model:
"/xxx/VAR/models/basic_var.py", line 113, in forward
    oup = flash_attn_func(q, k, v, dropout_p=dropout_p, softmax_scale=self.scale).view(B, L, C)
RuntimeError: FlashAttention only support fp16 and bf16 data type.

The problem comes from that while qkv is initially fp16, the scale_mul in line 101 of basic_var.py is fp32, which makes q and k become fp32.

update: F.normalize(q, dim=-1) also changes the dtype of q to fp32.

**Comment by keyu-tian** [comment]
Thanks @ThisisBillhe. I fixed this bug now in [74138aa](https://github.com/FoundationVision/VAR/commit/74138aa4229d97f0003d1bf70d03188d597d863a).
