### ISSUE TITLE
Question about the unconditional generation

### ISSUE THREAD

**Issue by minimini-1** [FoundationVision/VAR#31]
Hello Firstly, thanks for your great work and share the code including weights!

I have quite simple question about unconditional generation.
Referring to figure 4, I understood that the model can be passible to create image without giving class information in sos token.
![image](https://github.com/FoundationVision/VAR/assets/31647995/eec46516-f367-45ab-8d82-f369717c6253)

When referring to the demo_sample.ipynb file (in [autoregressive_infer_cfg funciton](https://github.com/FoundationVision/VAR/blob/2a49cad83ba4f0c06c258fac6a7b96039034b8e8/models/var.py#L147)), it seems that if label_B is None, it is not unconditional generation because it seems to randomly select from 1000 classes by sampling.
Is the without condition information in a paper the same as if label_B is None?

Also,
Referring to the [class_emb](https://github.com/FoundationVision/VAR/blob/2a49cad83ba4f0c06c258fac6a7b96039034b8e8/models/var.py#L61), the size of the embedding is 1001, which is 1 more than the imagenet class,
but when I generate an image using the 1000th class token, it seems like I get a pretty random image.
Is generating an image with this class index the same as without condition information?

Sincerely,
Jongmin

**Comment by keyu-tian** [comment]
thank you @minimini-1. The class_emb[1000] is the unconditional [sos] token. The class_emb[999] is the 1000-th class label token, and the class_emb[0] is the first class label token.

**Comment by minimini-1** [comment]
OK, thanks for your reply!
