### ISSUE TITLE
Question about the shared codebook

### ISSUE THREAD

**Issue by jiho314** [FoundationVision/VAR#34]
Hi, thanks for your wonderful work! I'm studying your work with big interest!

Is there any reason to use shared code book for multiple scales?
Intuitively, it seems there might be a possibility of performance gain via seperate codebook. (distinguishing the role of each codebook)
I wonder if you've tried unshared codebook.

Again, thank you!

**Comment by keyu-tian** [comment]
Thanks @jiho314. Although didn't try this, I also believe that an unshared one can yields better results because sharing the codebook would limit the model's expressive power. We use the shared codebook just for convince.

**Comment by jiho314** [comment]
Oh I got it. Thanks for your kind reply!
