### ISSUE TITLE
About progressive training

### ISSUE THREAD

**Issue by ParanoidHW** [FoundationVision/VAR#37]
Great work, author!
Since I found no training details in the paper (don't know if I've missed something), I wonder if there is any ablation study or difference on the performance of the progressive training compared to the naive one? Or it is just for efficient reasons like you mentioned in #29

**Comment by keyu-tian** [comment]
hi @ParanoidHW, yes we use progressive training for efficiency purpose. Full-scale training would yield better results but is much more slower.

**Comment by keyu-tian** [comment]
@ParanoidHW we try to make the resolution schedule similar to a exponential function starting from 1 and ending with 16 or 32 or 64.
