### ISSUE TITLE
fid

### ISSUE THREAD

**Issue by 21157651** [FoundationVision/VAR#39]
where is your eval code?  i want to calculate fid， thank you!

**Comment by keyu-tian** [comment]
hi @21157651 please use the hyperparameters in https://github.com/FoundationVision/VAR?tab=readme-ov-file#sampling--zero-shot-inference to sample 50000 images (50 images per class), save PNG files to a folder, and use the OpenAI's FID evaluation suit at https://github.com/openai/guided-diffusion/tree/main/evaluations to calculate FID.
