### ISSUE TITLE
Abnormal sample results with `demo_sample.ipynb`

### ISSUE THREAD

**Issue by karrykkk** [FoundationVision/VAR#41]
Thanks for sharing this nice work!

I tried to sample with `demo_sample.ipynb`  and [var_d16.pth](https://huggingface.co/FoundationVision/var/resolve/main/var_d16.pth) without any changes, but I got these abnormal results😢:
![output_image](https://github.com/FoundationVision/VAR/assets/113419191/0ff83564-647e-4092-ab99-ef7ff20fa086)

The following is my environment:
```
python                    3.10.14
torch                     2.0.1                    
torchvision               0.15.2                              
transformers              4.40.1               
triton                    2.0.0     
pillow                    10.3.0 
pytz                      2024.1 
typed-argument-parser     1.10.0             
```
Does this result from the precision problem or something else? I would appreciate it if you could help with this problem.🥺

**Comment by keyu-tian** [comment]
@karrykkk can you re-download the model's checkpoint file, and make sure all codes and demo_sample.ipynb are of the latest git commit?

**Comment by karrykkk** [comment]
Thanks for your reply!

 I have found the reason. It was because the key `scale` was not supported in `torch==2.0.1` and I deleted this key argument in https://github.com/FoundationVision/VAR/blob/a5cf0a16624d27b4c687b08f2a0ab006438452cc/models/basic_var.py#L117. When I update `torch` to 2.1.2 and use the origin code, the samples become normal.
