### ISSUE TITLE
How many GPU did you use for training?

### ISSUE THREAD

**Issue by daixiangzi** [FoundationVision/VAR#44]

**Comment by keyu-tian** [comment]
@daixiangzi Training VAR-d16 for 200 epochs on ImageNet 256x256 costs 2.5 days on 16 A100s. Training VAR-d30 for 350 epochs on ImageNet 512x512 with progressive training requires 256 A100 for around 4 days.

**Comment by daixiangzi** [comment]
> @daixiangzi Training VAR-d16 for 200 epochs on ImageNet 256x256 costs 2.5 days on 16 A100s. Training VAR-d30 for 350 epochs on ImageNet 512x512 with progressive training requires 256 A100 for around 4 days.

I train var-d16 on  ImageNet 256*256 on 16 a100,The training speed does not seem to be that fast.

**Comment by GooThinker** [comment]
I train var-d16 on ImageNet 256*256 on 8 a100. Why does the entire training take 11 days?
