### ISSUE TITLE
class VQVAE forward function error

### ISSUE THREAD

**Issue by woldier** [FoundationVision/VAR#46]
# CN:
VQVAE forward存在code 错误. 我发现 VectorQuantizer2.forward 返回三个参数. 而在https://github.com/FoundationVision/VAR/blob/a5cf0a16624d27b4c687b08f2a0ab006438452cc/models/vqvae.py#L58
接收了VectorQuantizer2.forward 返回的4个参数.
# EN:
VQVAE forward has a code error. I found that VectorQuantizer2.forward returns three parameters. And at https://github.com/FoundationVision/VAR/blob/a5cf0a16624d27b4c687b08f2a0ab006438452cc/models/vqvae.py#L58
receives four arguments from VectorQuantizer2.forward.

**Comment by keyu-tian** [comment]
hi @woldier, thank you and i fixed it in https://github.com/FoundationVision/VAR/commit/0029ecd537a4587e76b165dae04f9124b9391b66
