### ISSUE TITLE
about the training code

### ISSUE THREAD

**Issue by maowayne123** [FoundationVision/VAR#5]
thanks for your great work.
I see the training code is empty. when it will be release? Thank you!

**Comment by keyu-tian** [comment]
Thanks @maowayne123. If you're eager to see our model in action, our inference demo is ready for you at https://github.com/FoundationVision/VAR/blob/main/demo_sample.ipynb for our inference demo. I'm currently polishing up the training codes and they'll be ready in just a few days.

**Comment by luohao123** [comment]
Hi, am ask does the current training codes only for conditioned iamge geneation rather than text iamge generation?

Does the tokenizer training code release as well?

**Comment by keyu-tian** [comment]
Our training codes & scripts are released so im gonna close this. Thank you and hope you enjoy playing with VAR!

@luohao123 this codebase is only for label-to-image generation. VAE training codes will be released at https://github.com/FoundationVision/vae-pro soon.
