### ISSUE TITLE
请问下两个阶段ablation的细节

### ISSUE THREAD

**Issue by YilanWang** [FoundationVision/VAR#50]
请问作者,如果使用1) multi scale VQVAE(VQGAN) 但是采用VQGAN(taming transfomer)的transformer(clip?),
或者是使用2)  VQVAE(VQGAN) 但是gpt-like transformer, 这两种方式下的指标和原始VQGAN相比怎么样呢?

感觉2)有点难做实验,但还是想问问作者有没有做过这样的实验,感谢~~

**Comment by YilanWang** [comment]
哇,感谢大佬回复,作者要不啥时候搞个直播或者在b站上发个视频讲解呗,我看别的issue大家对细节的关注还挺多的

**Comment by YilanWang** [comment]
thx the author and I close the issue

**Comment by GewelsJI** [comment]
有一个问题就是，为什么要使用GPT2作为base呢，这个语言模型的选择有什么偏好没？或者 @keyu-tian 大佬有没有尝试过其他的语言模型呢，比如phi系列这一种的？

**Comment by iFighting** [comment]
@GewelsJI 
It is acceptable to use language models like GPT-2, LLAMA, or PHI; there are no fundamental differences among them.

**Comment by GewelsJI** [comment]
@iFighting Thanks.

Yes, you are right. Because all of them are autoregressive transformers. I still have a further question is, have you guys try lora-based training for GPT2?
