### ISSUE TITLE
Question about the cross-antropy loss average?

### ISSUE THREAD

**Issue by Yheechou** [FoundationVision/VAR#53]
What level of cross entropy loss in model training will have a good convergence effect

**Comment by YilanWang** [comment]
I'm not the author but you can try the entropy loss in CodeFormer

**Comment by keyu-tian** [comment]
@Yheechou cross entropy < 5.5 will look good. It's a 4096-category classification task.

**Comment by Yheechou** [comment]
thanks

**Comment by MiracleDance** [comment]
@keyu-tian So what level of 'Accm' may be good?
