### ISSUE TITLE
Training and Inference Scripts

### ISSUE THREAD

**Issue by achen46** [FoundationVision/VAR#6]
Hi, amazing work indeed ! 

I wonder, can you please release the training and inference scripts to be able to exactly reproduce your ImageNet 256x256 (and 512X512) results ? 

In addition, can you please provide information about the number of nodes/GPUs used for each of the ImageNet256 and ImageNet512 experiments ?

**Comment by keyu-tian** [comment]
ty @achen46! You can check out https://github.com/FoundationVision/VAR/blob/main/demo_sample.ipynb for our inference demo. For training cost I'll post more details on readme soon. Our most expensive 512x512 experiment use 256xA100 for around 3days.

**Comment by yyyouy** [comment]
Thank you for your good work! I also wonder, can you release the inference scripts to be able to reproduce your results? I just tried to reproduce your result on ImageNet 256 x 256 using your checkpoint. Thank you very much.

**Comment by achen46** [comment]
Hi @keyu-tian 

Thank you so much for providing the pointer ! 

As mentioned, I am interested in a (shell) script that I can run to start training the model and be able to reproduce the results. Basically, all I need is a self-contained script (with all hyper-parameters) that can be run. Also obviously, need to know how many nodes are used. 

256x256 ImageNet would suffice to begin with.

**Comment by morestart** [comment]
any update?

**Comment by keyu-tian** [comment]
@achen46 @yyyouy @morestart I got swamped with work recently, but the training codes & scripts are now out! I'll post more scripts for inference and zero-shot demos in the next. Feel free to drop an issue again if you run into any problems.

Thanks, and have fun with VAR!
