### ISSUE TITLE
T2I Generation

### ISSUE THREAD

**Issue by ucasyjz** [FoundationVision/VAR#64]
When the T2I code can be released, thank you

**Comment by keyu-tian** [comment]
We have no firm plans. I personally hope it will be ready by July.

**Comment by kl2004** [comment]
A new paper similar to VAR but for t2i: https://krennic999.github.io/STAR/

**Comment by ymz-123** [comment]
> A new paper similar to VAR but for t2i: https://krennic999.github.io/STAR/

no code release

**Comment by iFighting** [comment]
@ucasyjz please refer to our latest paper & repo: 
* https://github.com/FoundationVision/Infinity
* Paper Link: https://arxiv.org/abs/2412.04431
