### ISSUE TITLE
About testing Zero-shot generalizability

### ISSUE THREAD

**Issue by Youngwoo-git** [FoundationVision/VAR#7]
Thank you for sharing the code!

Just noticed the empty script in train.py, would like to know by when I can get an access to the training code. Also, is there any plan of releasing code regarding zero-shot generalization such as  Class-cond editing?

Thanks in advance!

**Comment by keyu-tian** [comment]
@Youngwoo-git yes i'm actively working on cleaning these codes. Both training codes and zero-shot demos wil be ok in this week. Stay tuned🍻!
