### ISSUE TITLE
About in-painting tasks

### ISSUE THREAD

**Issue by zhiyuanyou** [FoundationVision/VAR#74]
Hello, 

Thanks for your great work. 

I have found that the demo does not support in-painting tasks. So I wonder whether this repo contains the in-painting scripts ?

Thanks again.

**Comment by Ferenas** [comment]
Same question. I am curious about how to process inpainting task? Just simply set the masked regions as 0 and implement the teacher-force reconstruction?

**Comment by zijinY** [comment]
Same question, Did you try successfully ? Thanks.

**Comment by zhiyuanyou** [comment]
No. I finally use the in-painting model provided by Stable Diffusion.

**Comment by iFighting** [comment]
@zhiyuanyou @Ferenas @zijinY 
Thanks for your interest to our work, also apologize for late release of the code.
You can refer to this code: https://github.com/FoundationVision/VAR/blob/main/demo_zero_shot_edit.ipynb
