### ISSUE TITLE
Question about the training dataset - tokenzier

### ISSUE THREAD

**Issue by Lucky-Light-Sun** [FoundationVision/VAR#80]
Hi, I recently read your paper “Visual Autoregressive Modeling: Scalable Image Generation via Next-Scale Prediction” published in CVPR 2024. I am very interested in your method and have great respect for your contribution to the academic community.

We are currently doing some experiments and would like to ask you a question about the tokenizer part. **Is the pre-training dataset you are using OpenImage V6 or another version?** Current we are using OpenImage v6 to train tokenizer. So **do you think it's fair to compare with VAR tokenizer?**

Thank you again for your time and effort, and I look forward to your reply.

![image](https://github.com/user-attachments/assets/2edcff80-6d90-417f-8f05-38f9def42769)

**Comment by iFighting** [comment]
> Hi, I recently read your paper “Visual Autoregressive Modeling: Scalable Image Generation via Next-Scale Prediction” published in CVPR 2024. I am very interested in your method and have great respect for your contribution to the academic community.
> 
> We are currently doing some experiments and would like to ask you a question about the tokenizer part. **Is the pre-training dataset you are using OpenImage V6 or another version?** Current we are using OpenImage v6 to train tokenizer. So **do you think it's fair to compare with VAR tokenizer?**
> 
> Thank you again for your time and effort, and I look forward to your reply.
> 
> ![image](https://private-user-images.githubusercontent.com/60919766/355662149-2edcff80-6d90-417f-8f05-38f9def42769.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODM2MDAsIm5iZiI6MTczMzM4MzMwMCwicGF0aCI6Ii82MDkxOTc2Ni8zNTU2NjIxNDktMmVkY2ZmODAtNmQ5MC00MTdmLThmMDUtMzhmOWRlZjQyNzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA3MjE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMzg0MDdlNzFiZDU3NmRhM2UyOTMyOTQ1MjQyNDMxYTEzYzk1YTE5YzVlYzE4ZTljOTUzZGZjZThhZmE0MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zqh8T2R8u2R7osZArS98AKWfyQhZgE2V5laOS60nqAg)



> Hi, I recently read your paper “Visual Autoregressive Modeling: Scalable Image Generation via Next-Scale Prediction” published in CVPR 2024. I am very interested in your method and have great respect for your contribution to the academic community.
> 
> We are currently doing some experiments and would like to ask you a question about the tokenizer part. **Is the pre-training dataset you are using OpenImage V6 or another version?** Current we are using OpenImage v6 to train tokenizer. So **do you think it's fair to compare with VAR tokenizer?**
> 
> Thank you again for your time and effort, and I look forward to your reply.
> 
> ![image](https://private-user-images.githubusercontent.com/60919766/355662149-2edcff80-6d90-417f-8f05-38f9def42769.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODM2MDAsIm5iZiI6MTczMzM4MzMwMCwicGF0aCI6Ii82MDkxOTc2Ni8zNTU2NjIxNDktMmVkY2ZmODAtNmQ5MC00MTdmLThmMDUtMzhmOWRlZjQyNzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA3MjE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMzg0MDdlNzFiZDU3NmRhM2UyOTMyOTQ1MjQyNDMxYTEzYzk1YTE5YzVlYzE4ZTljOTUzZGZjZThhZmE0MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zqh8T2R8u2R7osZArS98AKWfyQhZgE2V5laOS60nqAg)

@Lucky-Light-Sun  
Sorry for late reply. 
The pre-training dataset we are using is OpenImage V6.
BTW, VAR is accepted as NeurIPS oral, not CVPR
