### ISSUE TITLE
class token replaces first token

### ISSUE THREAD

**Issue by cyw-3d** [FoundationVision/VAR#81]
Hi VAR teams, thanks for your insightful works!

I notice that when training VAR, you use the class token to replace the first token ouput by VQVAE, why don't you instead perpend the class token? Will this replacement results in loss of encoded information?

**Comment by Kaiwen-Zhu** [comment]
@cyw-3d I have the same question. This behavior slightly differs from that presented in Figure 4 in the paper. Have you found any explanation? Thank you!

**Comment by aopolin-lv** [comment]
> [@cyw-3d](https://github.com/cyw-3d) I have the same question. This behavior slightly differs from that presented in Figure 4 in the paper. Have you found any explanation? Thank you!

The same question. Have you resolved it? The replace operation does hurt the auto regreesive generation illustrated in Figure 4.
