### ISSUE TITLE
Training resource for multi-scale VAE

### ISSUE THREAD

**Issue by FRESHMAN2016** [FoundationVision/VAR#89]
Thank you for your excellent contribution to this community! 
I want to know how much resource did it take to train the vae in https://huggingface.co/FoundationVision/var/resolve/main/vae_ch160v4096z32.pth

**Comment by iFighting** [comment]
https://github.com/FoundationVision/vaex

**Comment by FRESHMAN2016** [comment]
Thank you for your reply!

**Comment by Youngwoo-git** [comment]
great work out there in [https://github.com/FoundationVision/vaex](https://github.com/FoundationVision/vaex)

any plan on releasing the training commands for vqvae? thanks in advance!
