### ISSUE TITLE
Inpainting codes

### ISSUE THREAD

**Issue by zijinY** [FoundationVision/VAR#92]
Thanks for your excellent work, any plan to release your inpaint code ?

**Comment by iFighting** [comment]
Thanks for your attention, we will release the inpaint code later.

**Comment by iFighting** [comment]
@zijinY 
Thanks for your interest to our work, also apologize for late release of the code.
You can refer to this code: https://github.com/FoundationVision/VAR/blob/main/demo_zero_shot_edit.ipynb
