### ISSUE TITLE
why say the time complexity of AR generation is  O(n^6) ?

### ISSUE THREAD

**Issue by kindernerd** [FoundationVision/VAR#96]
the paper says the time complexity of AR generation is  O(n^6) ，for the reason that 
" For the i-th (1 ≤i ≤n2) autoregressive iteration, the attention scores between each token and all other tokens need to be computed, which requires O(i^2) time. "
but for i-th ar, the attention scores between the current token and the other tokens need to be computed should requires O(i), how does O(i^2) come out?

**Comment by gameofdimension** [comment]
same question

**Comment by iFighting** [comment]
@gameofdimension @kindernerd 
Thanks for your attention.
In fact, the original computational complexity of self attention is O(i^2), if you use KVcache it's O(i).
