### ISSUE TITLE
Zero-shot generation test.

### ISSUE THREAD

**Issue by Capchenxi** [FoundationVision/VAR#99]
Thanks for your excellent work! 
Is there any plan of releasing code regarding zero-shot generalization for class-cond editing?
Thanks.

**Comment by iFighting** [comment]
@Capchenxi 
Thanks for your interest to our work, also apologize for late release of the code.
You can refer to this code: https://github.com/FoundationVision/VAR/blob/main/demo_zero_shot_edit.ipynb
